# fly.toml app configuration file generated for listmonk-app-1759010454 on 2025-09-27T23:01:27+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'listmonk-app-1759010454'
primary_region = 'lhr'

[build]

[env]
  LISTMONK_app__address = '0.0.0.0:9000'

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
