- [ ] Make the UI responsive
- [ ] Make buttons and links tabbable
- [ ] Add a "running campaigns" widget on the dashboard
- [ ] Add more analytics and stats
- [ ] Add bounce tracking
- [ ] Pause campaigns on % errors in addition to an absolute numbers
- [ ] Support DB migrations for easy upgrades
- [ ] Add materialized views for analytics and stats (and more?)
- [ ] Add GDPR-esque features (complete data download for end users, "forget me" option)
- [ ] Add user management and permissions
- [ ] Add tests
