name: KVSocial CI

on:
  pull_request:
    branches:
      - kvs-main
  push:
    branches:
      - kvs-main

permissions:
  contents: read

jobs:
  test:
    if: github.repository == 'KVSocial/listmonk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.1"
          cache: true

      - name: Run tests
        run: go test ./...
