package models

const (
	PermListGetAll            = "lists:get_all"
	PermListManageAll         = "lists:manage_all"
	PermListManage            = "list:manage"
	PermListGet               = "list:get"
	PermSubscribersGet        = "subscribers:get"
	PermSubscribersGetAll     = "subscribers:get_all"
	PermSubscribersManage     = "subscribers:manage"
	PermSubscribersImport     = "subscribers:import"
	PermSubscribersSqlQuery   = "subscribers:sql_query"
	PermTxSend                = "tx:send"
	PermCampaignsGet          = "campaigns:get"
	PermCampaignsGetAll       = "campaigns:get_all"
	PermCampaignsGetAnalytics = "campaigns:get_analytics"
	PermCampaignsManage       = "campaigns:manage"
	PermCampaignsManageAll    = "campaigns:manage_all"
	PermBouncesGet            = "bounces:get"
	PermBouncesManage         = "bounces:manage"
	PermWebhooksPostBounce    = "webhooks:post_bounce"
	PermMediaGet              = "media:get"
	PermMediaManage           = "media:manage"
	PermTemplatesGet          = "templates:get"
	PermTemplatesManage       = "templates:manage"
	PermUsersGet              = "users:get"
	PermUsersManage           = "users:manage"
	PermRolesGet              = "roles:get"
	PermRolesManage           = "roles:manage"
	PermSettingsGet           = "settings:get"
	PermSettingsManage        = "settings:manage"
	PermSettingsMaintain      = "settings:maintain"
)
